#include <gtest/gtest.h>
#include <cppasm.h>


TEST(Memory, m16_empty)
{
    m16 addr;

    EXPECT_EQ(addr.to_str(), "()");
}

TEST(Memory, m16_base)
{
    m16 addr;

    EXPECT_EQ(addr.base(EAX).to_str(), "(%eax)");
    EXPECT_EQ(addr.base(EBX).to_str(), "(%ebx)");
    EXPECT_EQ(addr.base(ECX).to_str(), "(%ecx)");
    EXPECT_EQ(addr.base(EDX).to_str(), "(%edx)");
    EXPECT_EQ(addr.base(EBP).to_str(), "(%ebp)");
    EXPECT_EQ(addr.base(ESI).to_str(), "(%esi)");
    EXPECT_EQ(addr.base(EDI).to_str(), "(%edi)");
    EXPECT_EQ(addr.base(ESP).to_str(), "(%esp)");
    EXPECT_EQ(addr.base(R8D).to_str(), "(%r8d)");
    EXPECT_EQ(addr.base(R9D).to_str(), "(%r9d)");
    EXPECT_EQ(addr.base(R10D).to_str(), "(%r10d)");
    EXPECT_EQ(addr.base(R11D).to_str(), "(%r11d)");
    EXPECT_EQ(addr.base(R12D).to_str(), "(%r12d)");
    EXPECT_EQ(addr.base(R13D).to_str(), "(%r13d)");
    EXPECT_EQ(addr.base(R14D).to_str(), "(%r14d)");
    EXPECT_EQ(addr.base(R15D).to_str(), "(%r15d)");
}

TEST(Memory, m16_base_index)
{
    m16 addr;

    EXPECT_EQ(addr.base(EAX).index(EAX).to_str(), "(%eax, %eax)");
    EXPECT_EQ(addr.base(EAX).index(EBX).to_str(), "(%eax, %ebx)");
    EXPECT_EQ(addr.base(EAX).index(ECX).to_str(), "(%eax, %ecx)");
    EXPECT_EQ(addr.base(EAX).index(EDX).to_str(), "(%eax, %edx)");
    EXPECT_EQ(addr.base(EAX).index(EBP).to_str(), "(%eax, %ebp)");
    EXPECT_EQ(addr.base(EAX).index(ESI).to_str(), "(%eax, %esi)");
    EXPECT_EQ(addr.base(EAX).index(EDI).to_str(), "(%eax, %edi)");
    EXPECT_EQ(addr.base(EAX).index(ESP).to_str(), "(%eax, %esp)");
    EXPECT_EQ(addr.base(EAX).index(R8D).to_str(), "(%eax, %r8d)");
    EXPECT_EQ(addr.base(EAX).index(R9D).to_str(), "(%eax, %r9d)");
    EXPECT_EQ(addr.base(EAX).index(R10D).to_str(), "(%eax, %r10d)");
    EXPECT_EQ(addr.base(EAX).index(R11D).to_str(), "(%eax, %r11d)");
    EXPECT_EQ(addr.base(EAX).index(R12D).to_str(), "(%eax, %r12d)");
    EXPECT_EQ(addr.base(EAX).index(R13D).to_str(), "(%eax, %r13d)");
    EXPECT_EQ(addr.base(EAX).index(R14D).to_str(), "(%eax, %r14d)");
    EXPECT_EQ(addr.base(EAX).index(R15D).to_str(), "(%eax, %r15d)");

    EXPECT_EQ(addr.base(EBX).index(EAX).to_str(), "(%ebx, %eax)");
    EXPECT_EQ(addr.base(EBX).index(EBX).to_str(), "(%ebx, %ebx)");
    EXPECT_EQ(addr.base(EBX).index(ECX).to_str(), "(%ebx, %ecx)");
    EXPECT_EQ(addr.base(EBX).index(EDX).to_str(), "(%ebx, %edx)");
    EXPECT_EQ(addr.base(EBX).index(EBP).to_str(), "(%ebx, %ebp)");
    EXPECT_EQ(addr.base(EBX).index(ESI).to_str(), "(%ebx, %esi)");
    EXPECT_EQ(addr.base(EBX).index(EDI).to_str(), "(%ebx, %edi)");
    EXPECT_EQ(addr.base(EBX).index(ESP).to_str(), "(%ebx, %esp)");
    EXPECT_EQ(addr.base(EBX).index(R8D).to_str(), "(%ebx, %r8d)");
    EXPECT_EQ(addr.base(EBX).index(R9D).to_str(), "(%ebx, %r9d)");
    EXPECT_EQ(addr.base(EBX).index(R10D).to_str(), "(%ebx, %r10d)");
    EXPECT_EQ(addr.base(EBX).index(R11D).to_str(), "(%ebx, %r11d)");
    EXPECT_EQ(addr.base(EBX).index(R12D).to_str(), "(%ebx, %r12d)");
    EXPECT_EQ(addr.base(EBX).index(R13D).to_str(), "(%ebx, %r13d)");
    EXPECT_EQ(addr.base(EBX).index(R14D).to_str(), "(%ebx, %r14d)");
    EXPECT_EQ(addr.base(EBX).index(R15D).to_str(), "(%ebx, %r15d)");

    EXPECT_EQ(addr.base(ECX).index(EAX).to_str(), "(%ecx, %eax)");
    EXPECT_EQ(addr.base(ECX).index(EBX).to_str(), "(%ecx, %ebx)");
    EXPECT_EQ(addr.base(ECX).index(ECX).to_str(), "(%ecx, %ecx)");
    EXPECT_EQ(addr.base(ECX).index(EDX).to_str(), "(%ecx, %edx)");
    EXPECT_EQ(addr.base(ECX).index(EBP).to_str(), "(%ecx, %ebp)");
    EXPECT_EQ(addr.base(ECX).index(ESI).to_str(), "(%ecx, %esi)");
    EXPECT_EQ(addr.base(ECX).index(EDI).to_str(), "(%ecx, %edi)");
    EXPECT_EQ(addr.base(ECX).index(ESP).to_str(), "(%ecx, %esp)");
    EXPECT_EQ(addr.base(ECX).index(R8D).to_str(), "(%ecx, %r8d)");
    EXPECT_EQ(addr.base(ECX).index(R9D).to_str(), "(%ecx, %r9d)");
    EXPECT_EQ(addr.base(ECX).index(R10D).to_str(), "(%ecx, %r10d)");
    EXPECT_EQ(addr.base(ECX).index(R11D).to_str(), "(%ecx, %r11d)");
    EXPECT_EQ(addr.base(ECX).index(R12D).to_str(), "(%ecx, %r12d)");
    EXPECT_EQ(addr.base(ECX).index(R13D).to_str(), "(%ecx, %r13d)");
    EXPECT_EQ(addr.base(ECX).index(R14D).to_str(), "(%ecx, %r14d)");
    EXPECT_EQ(addr.base(ECX).index(R15D).to_str(), "(%ecx, %r15d)");

    EXPECT_EQ(addr.base(EDX).index(EAX).to_str(), "(%edx, %eax)");
    EXPECT_EQ(addr.base(EDX).index(EBX).to_str(), "(%edx, %ebx)");
    EXPECT_EQ(addr.base(EDX).index(ECX).to_str(), "(%edx, %ecx)");
    EXPECT_EQ(addr.base(EDX).index(EDX).to_str(), "(%edx, %edx)");
    EXPECT_EQ(addr.base(EDX).index(EBP).to_str(), "(%edx, %ebp)");
    EXPECT_EQ(addr.base(EDX).index(ESI).to_str(), "(%edx, %esi)");
    EXPECT_EQ(addr.base(EDX).index(EDI).to_str(), "(%edx, %edi)");
    EXPECT_EQ(addr.base(EDX).index(ESP).to_str(), "(%edx, %esp)");
    EXPECT_EQ(addr.base(EDX).index(R8D).to_str(), "(%edx, %r8d)");
    EXPECT_EQ(addr.base(EDX).index(R9D).to_str(), "(%edx, %r9d)");
    EXPECT_EQ(addr.base(EDX).index(R10D).to_str(), "(%edx, %r10d)");
    EXPECT_EQ(addr.base(EDX).index(R11D).to_str(), "(%edx, %r11d)");
    EXPECT_EQ(addr.base(EDX).index(R12D).to_str(), "(%edx, %r12d)");
    EXPECT_EQ(addr.base(EDX).index(R13D).to_str(), "(%edx, %r13d)");
    EXPECT_EQ(addr.base(EDX).index(R14D).to_str(), "(%edx, %r14d)");
    EXPECT_EQ(addr.base(EDX).index(R15D).to_str(), "(%edx, %r15d)");

    EXPECT_EQ(addr.base(EBP).index(EAX).to_str(), "(%ebp, %eax)");
    EXPECT_EQ(addr.base(EBP).index(EBX).to_str(), "(%ebp, %ebx)");
    EXPECT_EQ(addr.base(EBP).index(ECX).to_str(), "(%ebp, %ecx)");
    EXPECT_EQ(addr.base(EBP).index(EDX).to_str(), "(%ebp, %edx)");
    EXPECT_EQ(addr.base(EBP).index(EBP).to_str(), "(%ebp, %ebp)");
    EXPECT_EQ(addr.base(EBP).index(ESI).to_str(), "(%ebp, %esi)");
    EXPECT_EQ(addr.base(EBP).index(EDI).to_str(), "(%ebp, %edi)");
    EXPECT_EQ(addr.base(EBP).index(ESP).to_str(), "(%ebp, %esp)");
    EXPECT_EQ(addr.base(EBP).index(R8D).to_str(), "(%ebp, %r8d)");
    EXPECT_EQ(addr.base(EBP).index(R9D).to_str(), "(%ebp, %r9d)");
    EXPECT_EQ(addr.base(EBP).index(R10D).to_str(), "(%ebp, %r10d)");
    EXPECT_EQ(addr.base(EBP).index(R11D).to_str(), "(%ebp, %r11d)");
    EXPECT_EQ(addr.base(EBP).index(R12D).to_str(), "(%ebp, %r12d)");
    EXPECT_EQ(addr.base(EBP).index(R13D).to_str(), "(%ebp, %r13d)");
    EXPECT_EQ(addr.base(EBP).index(R14D).to_str(), "(%ebp, %r14d)");
    EXPECT_EQ(addr.base(EBP).index(R15D).to_str(), "(%ebp, %r15d)");

    EXPECT_EQ(addr.base(ESI).index(EAX).to_str(), "(%esi, %eax)");
    EXPECT_EQ(addr.base(ESI).index(EBX).to_str(), "(%esi, %ebx)");
    EXPECT_EQ(addr.base(ESI).index(ECX).to_str(), "(%esi, %ecx)");
    EXPECT_EQ(addr.base(ESI).index(EDX).to_str(), "(%esi, %edx)");
    EXPECT_EQ(addr.base(ESI).index(EBP).to_str(), "(%esi, %ebp)");
    EXPECT_EQ(addr.base(ESI).index(ESI).to_str(), "(%esi, %esi)");
    EXPECT_EQ(addr.base(ESI).index(EDI).to_str(), "(%esi, %edi)");
    EXPECT_EQ(addr.base(ESI).index(ESP).to_str(), "(%esi, %esp)");
    EXPECT_EQ(addr.base(ESI).index(R8D).to_str(), "(%esi, %r8d)");
    EXPECT_EQ(addr.base(ESI).index(R9D).to_str(), "(%esi, %r9d)");
    EXPECT_EQ(addr.base(ESI).index(R10D).to_str(), "(%esi, %r10d)");
    EXPECT_EQ(addr.base(ESI).index(R11D).to_str(), "(%esi, %r11d)");
    EXPECT_EQ(addr.base(ESI).index(R12D).to_str(), "(%esi, %r12d)");
    EXPECT_EQ(addr.base(ESI).index(R13D).to_str(), "(%esi, %r13d)");
    EXPECT_EQ(addr.base(ESI).index(R14D).to_str(), "(%esi, %r14d)");
    EXPECT_EQ(addr.base(ESI).index(R15D).to_str(), "(%esi, %r15d)");

    EXPECT_EQ(addr.base(EDI).index(EAX).to_str(), "(%edi, %eax)");
    EXPECT_EQ(addr.base(EDI).index(EBX).to_str(), "(%edi, %ebx)");
    EXPECT_EQ(addr.base(EDI).index(ECX).to_str(), "(%edi, %ecx)");
    EXPECT_EQ(addr.base(EDI).index(EDX).to_str(), "(%edi, %edx)");
    EXPECT_EQ(addr.base(EDI).index(EBP).to_str(), "(%edi, %ebp)");
    EXPECT_EQ(addr.base(EDI).index(ESI).to_str(), "(%edi, %esi)");
    EXPECT_EQ(addr.base(EDI).index(EDI).to_str(), "(%edi, %edi)");
    EXPECT_EQ(addr.base(EDI).index(ESP).to_str(), "(%edi, %esp)");
    EXPECT_EQ(addr.base(EDI).index(R8D).to_str(), "(%edi, %r8d)");
    EXPECT_EQ(addr.base(EDI).index(R9D).to_str(), "(%edi, %r9d)");
    EXPECT_EQ(addr.base(EDI).index(R10D).to_str(), "(%edi, %r10d)");
    EXPECT_EQ(addr.base(EDI).index(R11D).to_str(), "(%edi, %r11d)");
    EXPECT_EQ(addr.base(EDI).index(R12D).to_str(), "(%edi, %r12d)");
    EXPECT_EQ(addr.base(EDI).index(R13D).to_str(), "(%edi, %r13d)");
    EXPECT_EQ(addr.base(EDI).index(R14D).to_str(), "(%edi, %r14d)");
    EXPECT_EQ(addr.base(EDI).index(R15D).to_str(), "(%edi, %r15d)");

    EXPECT_EQ(addr.base(ESP).index(EAX).to_str(), "(%esp, %eax)");
    EXPECT_EQ(addr.base(ESP).index(EBX).to_str(), "(%esp, %ebx)");
    EXPECT_EQ(addr.base(ESP).index(ECX).to_str(), "(%esp, %ecx)");
    EXPECT_EQ(addr.base(ESP).index(EDX).to_str(), "(%esp, %edx)");
    EXPECT_EQ(addr.base(ESP).index(EBP).to_str(), "(%esp, %ebp)");
    EXPECT_EQ(addr.base(ESP).index(ESI).to_str(), "(%esp, %esi)");
    EXPECT_EQ(addr.base(ESP).index(EDI).to_str(), "(%esp, %edi)");
    EXPECT_EQ(addr.base(ESP).index(ESP).to_str(), "(%esp, %esp)");
    EXPECT_EQ(addr.base(ESP).index(R8D).to_str(), "(%esp, %r8d)");
    EXPECT_EQ(addr.base(ESP).index(R9D).to_str(), "(%esp, %r9d)");
    EXPECT_EQ(addr.base(ESP).index(R10D).to_str(), "(%esp, %r10d)");
    EXPECT_EQ(addr.base(ESP).index(R11D).to_str(), "(%esp, %r11d)");
    EXPECT_EQ(addr.base(ESP).index(R12D).to_str(), "(%esp, %r12d)");
    EXPECT_EQ(addr.base(ESP).index(R13D).to_str(), "(%esp, %r13d)");
    EXPECT_EQ(addr.base(ESP).index(R14D).to_str(), "(%esp, %r14d)");
    EXPECT_EQ(addr.base(ESP).index(R15D).to_str(), "(%esp, %r15d)");

    EXPECT_EQ(addr.base(R8D).index(EAX).to_str(), "(%r8d, %eax)");
    EXPECT_EQ(addr.base(R8D).index(EBX).to_str(), "(%r8d, %ebx)");
    EXPECT_EQ(addr.base(R8D).index(ECX).to_str(), "(%r8d, %ecx)");
    EXPECT_EQ(addr.base(R8D).index(EDX).to_str(), "(%r8d, %edx)");
    EXPECT_EQ(addr.base(R8D).index(EBP).to_str(), "(%r8d, %ebp)");
    EXPECT_EQ(addr.base(R8D).index(ESI).to_str(), "(%r8d, %esi)");
    EXPECT_EQ(addr.base(R8D).index(EDI).to_str(), "(%r8d, %edi)");
    EXPECT_EQ(addr.base(R8D).index(ESP).to_str(), "(%r8d, %esp)");
    EXPECT_EQ(addr.base(R8D).index(R8D).to_str(), "(%r8d, %r8d)");
    EXPECT_EQ(addr.base(R8D).index(R9D).to_str(), "(%r8d, %r9d)");
    EXPECT_EQ(addr.base(R8D).index(R10D).to_str(), "(%r8d, %r10d)");
    EXPECT_EQ(addr.base(R8D).index(R11D).to_str(), "(%r8d, %r11d)");
    EXPECT_EQ(addr.base(R8D).index(R12D).to_str(), "(%r8d, %r12d)");
    EXPECT_EQ(addr.base(R8D).index(R13D).to_str(), "(%r8d, %r13d)");
    EXPECT_EQ(addr.base(R8D).index(R14D).to_str(), "(%r8d, %r14d)");
    EXPECT_EQ(addr.base(R8D).index(R15D).to_str(), "(%r8d, %r15d)");

    EXPECT_EQ(addr.base(R9D).index(EAX).to_str(), "(%r9d, %eax)");
    EXPECT_EQ(addr.base(R9D).index(EBX).to_str(), "(%r9d, %ebx)");
    EXPECT_EQ(addr.base(R9D).index(ECX).to_str(), "(%r9d, %ecx)");
    EXPECT_EQ(addr.base(R9D).index(EDX).to_str(), "(%r9d, %edx)");
    EXPECT_EQ(addr.base(R9D).index(EBP).to_str(), "(%r9d, %ebp)");
    EXPECT_EQ(addr.base(R9D).index(ESI).to_str(), "(%r9d, %esi)");
    EXPECT_EQ(addr.base(R9D).index(EDI).to_str(), "(%r9d, %edi)");
    EXPECT_EQ(addr.base(R9D).index(ESP).to_str(), "(%r9d, %esp)");
    EXPECT_EQ(addr.base(R9D).index(R8D).to_str(), "(%r9d, %r8d)");
    EXPECT_EQ(addr.base(R9D).index(R9D).to_str(), "(%r9d, %r9d)");
    EXPECT_EQ(addr.base(R9D).index(R10D).to_str(), "(%r9d, %r10d)");
    EXPECT_EQ(addr.base(R9D).index(R11D).to_str(), "(%r9d, %r11d)");
    EXPECT_EQ(addr.base(R9D).index(R12D).to_str(), "(%r9d, %r12d)");
    EXPECT_EQ(addr.base(R9D).index(R13D).to_str(), "(%r9d, %r13d)");
    EXPECT_EQ(addr.base(R9D).index(R14D).to_str(), "(%r9d, %r14d)");
    EXPECT_EQ(addr.base(R9D).index(R15D).to_str(), "(%r9d, %r15d)");

    EXPECT_EQ(addr.base(R10D).index(EAX).to_str(), "(%r10d, %eax)");
    EXPECT_EQ(addr.base(R10D).index(EBX).to_str(), "(%r10d, %ebx)");
    EXPECT_EQ(addr.base(R10D).index(ECX).to_str(), "(%r10d, %ecx)");
    EXPECT_EQ(addr.base(R10D).index(EDX).to_str(), "(%r10d, %edx)");
    EXPECT_EQ(addr.base(R10D).index(EBP).to_str(), "(%r10d, %ebp)");
    EXPECT_EQ(addr.base(R10D).index(ESI).to_str(), "(%r10d, %esi)");
    EXPECT_EQ(addr.base(R10D).index(EDI).to_str(), "(%r10d, %edi)");
    EXPECT_EQ(addr.base(R10D).index(ESP).to_str(), "(%r10d, %esp)");
    EXPECT_EQ(addr.base(R10D).index(R8D).to_str(), "(%r10d, %r8d)");
    EXPECT_EQ(addr.base(R10D).index(R9D).to_str(), "(%r10d, %r9d)");
    EXPECT_EQ(addr.base(R10D).index(R10D).to_str(), "(%r10d, %r10d)");
    EXPECT_EQ(addr.base(R10D).index(R11D).to_str(), "(%r10d, %r11d)");
    EXPECT_EQ(addr.base(R10D).index(R12D).to_str(), "(%r10d, %r12d)");
    EXPECT_EQ(addr.base(R10D).index(R13D).to_str(), "(%r10d, %r13d)");
    EXPECT_EQ(addr.base(R10D).index(R14D).to_str(), "(%r10d, %r14d)");
    EXPECT_EQ(addr.base(R10D).index(R15D).to_str(), "(%r10d, %r15d)");

    EXPECT_EQ(addr.base(R11D).index(EAX).to_str(), "(%r11d, %eax)");
    EXPECT_EQ(addr.base(R11D).index(EBX).to_str(), "(%r11d, %ebx)");
    EXPECT_EQ(addr.base(R11D).index(ECX).to_str(), "(%r11d, %ecx)");
    EXPECT_EQ(addr.base(R11D).index(EDX).to_str(), "(%r11d, %edx)");
    EXPECT_EQ(addr.base(R11D).index(EBP).to_str(), "(%r11d, %ebp)");
    EXPECT_EQ(addr.base(R11D).index(ESI).to_str(), "(%r11d, %esi)");
    EXPECT_EQ(addr.base(R11D).index(EDI).to_str(), "(%r11d, %edi)");
    EXPECT_EQ(addr.base(R11D).index(ESP).to_str(), "(%r11d, %esp)");
    EXPECT_EQ(addr.base(R11D).index(R8D).to_str(), "(%r11d, %r8d)");
    EXPECT_EQ(addr.base(R11D).index(R9D).to_str(), "(%r11d, %r9d)");
    EXPECT_EQ(addr.base(R11D).index(R10D).to_str(), "(%r11d, %r10d)");
    EXPECT_EQ(addr.base(R11D).index(R11D).to_str(), "(%r11d, %r11d)");
    EXPECT_EQ(addr.base(R11D).index(R12D).to_str(), "(%r11d, %r12d)");
    EXPECT_EQ(addr.base(R11D).index(R13D).to_str(), "(%r11d, %r13d)");
    EXPECT_EQ(addr.base(R11D).index(R14D).to_str(), "(%r11d, %r14d)");
    EXPECT_EQ(addr.base(R11D).index(R15D).to_str(), "(%r11d, %r15d)");

    EXPECT_EQ(addr.base(R12D).index(EAX).to_str(), "(%r12d, %eax)");
    EXPECT_EQ(addr.base(R12D).index(EBX).to_str(), "(%r12d, %ebx)");
    EXPECT_EQ(addr.base(R12D).index(ECX).to_str(), "(%r12d, %ecx)");
    EXPECT_EQ(addr.base(R12D).index(EDX).to_str(), "(%r12d, %edx)");
    EXPECT_EQ(addr.base(R12D).index(EBP).to_str(), "(%r12d, %ebp)");
    EXPECT_EQ(addr.base(R12D).index(ESI).to_str(), "(%r12d, %esi)");
    EXPECT_EQ(addr.base(R12D).index(EDI).to_str(), "(%r12d, %edi)");
    EXPECT_EQ(addr.base(R12D).index(ESP).to_str(), "(%r12d, %esp)");
    EXPECT_EQ(addr.base(R12D).index(R8D).to_str(), "(%r12d, %r8d)");
    EXPECT_EQ(addr.base(R12D).index(R9D).to_str(), "(%r12d, %r9d)");
    EXPECT_EQ(addr.base(R12D).index(R10D).to_str(), "(%r12d, %r10d)");
    EXPECT_EQ(addr.base(R12D).index(R11D).to_str(), "(%r12d, %r11d)");
    EXPECT_EQ(addr.base(R12D).index(R12D).to_str(), "(%r12d, %r12d)");
    EXPECT_EQ(addr.base(R12D).index(R13D).to_str(), "(%r12d, %r13d)");
    EXPECT_EQ(addr.base(R12D).index(R14D).to_str(), "(%r12d, %r14d)");
    EXPECT_EQ(addr.base(R12D).index(R15D).to_str(), "(%r12d, %r15d)");

    EXPECT_EQ(addr.base(R13D).index(EAX).to_str(), "(%r13d, %eax)");
    EXPECT_EQ(addr.base(R13D).index(EBX).to_str(), "(%r13d, %ebx)");
    EXPECT_EQ(addr.base(R13D).index(ECX).to_str(), "(%r13d, %ecx)");
    EXPECT_EQ(addr.base(R13D).index(EDX).to_str(), "(%r13d, %edx)");
    EXPECT_EQ(addr.base(R13D).index(EBP).to_str(), "(%r13d, %ebp)");
    EXPECT_EQ(addr.base(R13D).index(ESI).to_str(), "(%r13d, %esi)");
    EXPECT_EQ(addr.base(R13D).index(EDI).to_str(), "(%r13d, %edi)");
    EXPECT_EQ(addr.base(R13D).index(ESP).to_str(), "(%r13d, %esp)");
    EXPECT_EQ(addr.base(R13D).index(R8D).to_str(), "(%r13d, %r8d)");
    EXPECT_EQ(addr.base(R13D).index(R9D).to_str(), "(%r13d, %r9d)");
    EXPECT_EQ(addr.base(R13D).index(R10D).to_str(), "(%r13d, %r10d)");
    EXPECT_EQ(addr.base(R13D).index(R11D).to_str(), "(%r13d, %r11d)");
    EXPECT_EQ(addr.base(R13D).index(R12D).to_str(), "(%r13d, %r12d)");
    EXPECT_EQ(addr.base(R13D).index(R13D).to_str(), "(%r13d, %r13d)");
    EXPECT_EQ(addr.base(R13D).index(R14D).to_str(), "(%r13d, %r14d)");
    EXPECT_EQ(addr.base(R13D).index(R15D).to_str(), "(%r13d, %r15d)");

    EXPECT_EQ(addr.base(R14D).index(EAX).to_str(), "(%r14d, %eax)");
    EXPECT_EQ(addr.base(R14D).index(EBX).to_str(), "(%r14d, %ebx)");
    EXPECT_EQ(addr.base(R14D).index(ECX).to_str(), "(%r14d, %ecx)");
    EXPECT_EQ(addr.base(R14D).index(EDX).to_str(), "(%r14d, %edx)");
    EXPECT_EQ(addr.base(R14D).index(EBP).to_str(), "(%r14d, %ebp)");
    EXPECT_EQ(addr.base(R14D).index(ESI).to_str(), "(%r14d, %esi)");
    EXPECT_EQ(addr.base(R14D).index(EDI).to_str(), "(%r14d, %edi)");
    EXPECT_EQ(addr.base(R14D).index(ESP).to_str(), "(%r14d, %esp)");
    EXPECT_EQ(addr.base(R14D).index(R8D).to_str(), "(%r14d, %r8d)");
    EXPECT_EQ(addr.base(R14D).index(R9D).to_str(), "(%r14d, %r9d)");
    EXPECT_EQ(addr.base(R14D).index(R10D).to_str(), "(%r14d, %r10d)");
    EXPECT_EQ(addr.base(R14D).index(R11D).to_str(), "(%r14d, %r11d)");
    EXPECT_EQ(addr.base(R14D).index(R12D).to_str(), "(%r14d, %r12d)");
    EXPECT_EQ(addr.base(R14D).index(R13D).to_str(), "(%r14d, %r13d)");
    EXPECT_EQ(addr.base(R14D).index(R14D).to_str(), "(%r14d, %r14d)");
    EXPECT_EQ(addr.base(R14D).index(R15D).to_str(), "(%r14d, %r15d)");

    EXPECT_EQ(addr.base(R15D).index(EAX).to_str(), "(%r15d, %eax)");
    EXPECT_EQ(addr.base(R15D).index(EBX).to_str(), "(%r15d, %ebx)");
    EXPECT_EQ(addr.base(R15D).index(ECX).to_str(), "(%r15d, %ecx)");
    EXPECT_EQ(addr.base(R15D).index(EDX).to_str(), "(%r15d, %edx)");
    EXPECT_EQ(addr.base(R15D).index(EBP).to_str(), "(%r15d, %ebp)");
    EXPECT_EQ(addr.base(R15D).index(ESI).to_str(), "(%r15d, %esi)");
    EXPECT_EQ(addr.base(R15D).index(EDI).to_str(), "(%r15d, %edi)");
    EXPECT_EQ(addr.base(R15D).index(ESP).to_str(), "(%r15d, %esp)");
    EXPECT_EQ(addr.base(R15D).index(R8D).to_str(), "(%r15d, %r8d)");
    EXPECT_EQ(addr.base(R15D).index(R9D).to_str(), "(%r15d, %r9d)");
    EXPECT_EQ(addr.base(R15D).index(R10D).to_str(), "(%r15d, %r10d)");
    EXPECT_EQ(addr.base(R15D).index(R11D).to_str(), "(%r15d, %r11d)");
    EXPECT_EQ(addr.base(R15D).index(R12D).to_str(), "(%r15d, %r12d)");
    EXPECT_EQ(addr.base(R15D).index(R13D).to_str(), "(%r15d, %r13d)");
    EXPECT_EQ(addr.base(R15D).index(R14D).to_str(), "(%r15d, %r14d)");
    EXPECT_EQ(addr.base(R15D).index(R15D).to_str(), "(%r15d, %r15d)");
}

TEST(Memory, m16_base_index_scale)
{
    m16 addr;

    EXPECT_EQ(addr.base(EAX).index(EAX).scale(1).to_str(), "(%eax, %eax, 1)");
    EXPECT_EQ(addr.base(EAX).index(EBX).scale(2).to_str(), "(%eax, %ebx, 2)");
    EXPECT_EQ(addr.base(EAX).index(ECX).scale(4).to_str(), "(%eax, %ecx, 4)");
    EXPECT_EQ(addr.base(EAX).index(EDX).scale(8).to_str(), "(%eax, %edx, 8)");
    EXPECT_EQ(addr.base(EAX).index(EBP).scale(1).to_str(), "(%eax, %ebp, 1)");
    EXPECT_EQ(addr.base(EAX).index(ESI).scale(2).to_str(), "(%eax, %esi, 2)");
    EXPECT_EQ(addr.base(EAX).index(EDI).scale(4).to_str(), "(%eax, %edi, 4)");
    EXPECT_EQ(addr.base(EAX).index(ESP).scale(8).to_str(), "(%eax, %esp, 8)");
    EXPECT_EQ(addr.base(EAX).index(R8D).scale(1).to_str(), "(%eax, %r8d, 1)");
    EXPECT_EQ(addr.base(EAX).index(R9D).scale(2).to_str(), "(%eax, %r9d, 2)");
    EXPECT_EQ(addr.base(EAX).index(R10D).scale(4).to_str(), "(%eax, %r10d, 4)");
    EXPECT_EQ(addr.base(EAX).index(R11D).scale(8).to_str(), "(%eax, %r11d, 8)");
    EXPECT_EQ(addr.base(EAX).index(R12D).scale(1).to_str(), "(%eax, %r12d, 1)");
    EXPECT_EQ(addr.base(EAX).index(R13D).scale(2).to_str(), "(%eax, %r13d, 2)");
    EXPECT_EQ(addr.base(EAX).index(R14D).scale(4).to_str(), "(%eax, %r14d, 4)");
    EXPECT_EQ(addr.base(EAX).index(R15D).scale(8).to_str(), "(%eax, %r15d, 8)");

    EXPECT_EQ(addr.base(EBX).index(EAX).scale(1).to_str(), "(%ebx, %eax, 1)");
    EXPECT_EQ(addr.base(EBX).index(EBX).scale(2).to_str(), "(%ebx, %ebx, 2)");
    EXPECT_EQ(addr.base(EBX).index(ECX).scale(4).to_str(), "(%ebx, %ecx, 4)");
    EXPECT_EQ(addr.base(EBX).index(EDX).scale(8).to_str(), "(%ebx, %edx, 8)");
    EXPECT_EQ(addr.base(EBX).index(EBP).scale(1).to_str(), "(%ebx, %ebp, 1)");
    EXPECT_EQ(addr.base(EBX).index(ESI).scale(2).to_str(), "(%ebx, %esi, 2)");
    EXPECT_EQ(addr.base(EBX).index(EDI).scale(4).to_str(), "(%ebx, %edi, 4)");
    EXPECT_EQ(addr.base(EBX).index(ESP).scale(8).to_str(), "(%ebx, %esp, 8)");
    EXPECT_EQ(addr.base(EBX).index(R8D).scale(1).to_str(), "(%ebx, %r8d, 1)");
    EXPECT_EQ(addr.base(EBX).index(R9D).scale(2).to_str(), "(%ebx, %r9d, 2)");
    EXPECT_EQ(addr.base(EBX).index(R10D).scale(4).to_str(), "(%ebx, %r10d, 4)");
    EXPECT_EQ(addr.base(EBX).index(R11D).scale(8).to_str(), "(%ebx, %r11d, 8)");
    EXPECT_EQ(addr.base(EBX).index(R12D).scale(1).to_str(), "(%ebx, %r12d, 1)");
    EXPECT_EQ(addr.base(EBX).index(R13D).scale(2).to_str(), "(%ebx, %r13d, 2)");
    EXPECT_EQ(addr.base(EBX).index(R14D).scale(4).to_str(), "(%ebx, %r14d, 4)");
    EXPECT_EQ(addr.base(EBX).index(R15D).scale(8).to_str(), "(%ebx, %r15d, 8)");

    EXPECT_EQ(addr.base(ECX).index(EAX).scale(1).to_str(), "(%ecx, %eax, 1)");
    EXPECT_EQ(addr.base(ECX).index(EBX).scale(2).to_str(), "(%ecx, %ebx, 2)");
    EXPECT_EQ(addr.base(ECX).index(ECX).scale(4).to_str(), "(%ecx, %ecx, 4)");
    EXPECT_EQ(addr.base(ECX).index(EDX).scale(8).to_str(), "(%ecx, %edx, 8)");
    EXPECT_EQ(addr.base(ECX).index(EBP).scale(1).to_str(), "(%ecx, %ebp, 1)");
    EXPECT_EQ(addr.base(ECX).index(ESI).scale(2).to_str(), "(%ecx, %esi, 2)");
    EXPECT_EQ(addr.base(ECX).index(EDI).scale(4).to_str(), "(%ecx, %edi, 4)");
    EXPECT_EQ(addr.base(ECX).index(ESP).scale(8).to_str(), "(%ecx, %esp, 8)");
    EXPECT_EQ(addr.base(ECX).index(R8D).scale(1).to_str(), "(%ecx, %r8d, 1)");
    EXPECT_EQ(addr.base(ECX).index(R9D).scale(2).to_str(), "(%ecx, %r9d, 2)");
    EXPECT_EQ(addr.base(ECX).index(R10D).scale(4).to_str(), "(%ecx, %r10d, 4)");
    EXPECT_EQ(addr.base(ECX).index(R11D).scale(8).to_str(), "(%ecx, %r11d, 8)");
    EXPECT_EQ(addr.base(ECX).index(R12D).scale(1).to_str(), "(%ecx, %r12d, 1)");
    EXPECT_EQ(addr.base(ECX).index(R13D).scale(2).to_str(), "(%ecx, %r13d, 2)");
    EXPECT_EQ(addr.base(ECX).index(R14D).scale(4).to_str(), "(%ecx, %r14d, 4)");
    EXPECT_EQ(addr.base(ECX).index(R15D).scale(8).to_str(), "(%ecx, %r15d, 8)");

    EXPECT_EQ(addr.base(EDX).index(EAX).scale(1).to_str(), "(%edx, %eax, 1)");
    EXPECT_EQ(addr.base(EDX).index(EBX).scale(2).to_str(), "(%edx, %ebx, 2)");
    EXPECT_EQ(addr.base(EDX).index(ECX).scale(4).to_str(), "(%edx, %ecx, 4)");
    EXPECT_EQ(addr.base(EDX).index(EDX).scale(8).to_str(), "(%edx, %edx, 8)");
    EXPECT_EQ(addr.base(EDX).index(EBP).scale(1).to_str(), "(%edx, %ebp, 1)");
    EXPECT_EQ(addr.base(EDX).index(ESI).scale(2).to_str(), "(%edx, %esi, 2)");
    EXPECT_EQ(addr.base(EDX).index(EDI).scale(4).to_str(), "(%edx, %edi, 4)");
    EXPECT_EQ(addr.base(EDX).index(ESP).scale(8).to_str(), "(%edx, %esp, 8)");
    EXPECT_EQ(addr.base(EDX).index(R8D).scale(1).to_str(), "(%edx, %r8d, 1)");
    EXPECT_EQ(addr.base(EDX).index(R9D).scale(2).to_str(), "(%edx, %r9d, 2)");
    EXPECT_EQ(addr.base(EDX).index(R10D).scale(4).to_str(), "(%edx, %r10d, 4)");
    EXPECT_EQ(addr.base(EDX).index(R11D).scale(8).to_str(), "(%edx, %r11d, 8)");
    EXPECT_EQ(addr.base(EDX).index(R12D).scale(1).to_str(), "(%edx, %r12d, 1)");
    EXPECT_EQ(addr.base(EDX).index(R13D).scale(2).to_str(), "(%edx, %r13d, 2)");
    EXPECT_EQ(addr.base(EDX).index(R14D).scale(4).to_str(), "(%edx, %r14d, 4)");
    EXPECT_EQ(addr.base(EDX).index(R15D).scale(8).to_str(), "(%edx, %r15d, 8)");

    EXPECT_EQ(addr.base(EBP).index(EAX).scale(1).to_str(), "(%ebp, %eax, 1)");
    EXPECT_EQ(addr.base(EBP).index(EBX).scale(2).to_str(), "(%ebp, %ebx, 2)");
    EXPECT_EQ(addr.base(EBP).index(ECX).scale(4).to_str(), "(%ebp, %ecx, 4)");
    EXPECT_EQ(addr.base(EBP).index(EDX).scale(8).to_str(), "(%ebp, %edx, 8)");
    EXPECT_EQ(addr.base(EBP).index(EBP).scale(1).to_str(), "(%ebp, %ebp, 1)");
    EXPECT_EQ(addr.base(EBP).index(ESI).scale(2).to_str(), "(%ebp, %esi, 2)");
    EXPECT_EQ(addr.base(EBP).index(EDI).scale(4).to_str(), "(%ebp, %edi, 4)");
    EXPECT_EQ(addr.base(EBP).index(ESP).scale(8).to_str(), "(%ebp, %esp, 8)");
    EXPECT_EQ(addr.base(EBP).index(R8D).scale(1).to_str(), "(%ebp, %r8d, 1)");
    EXPECT_EQ(addr.base(EBP).index(R9D).scale(2).to_str(), "(%ebp, %r9d, 2)");
    EXPECT_EQ(addr.base(EBP).index(R10D).scale(4).to_str(), "(%ebp, %r10d, 4)");
    EXPECT_EQ(addr.base(EBP).index(R11D).scale(8).to_str(), "(%ebp, %r11d, 8)");
    EXPECT_EQ(addr.base(EBP).index(R12D).scale(1).to_str(), "(%ebp, %r12d, 1)");
    EXPECT_EQ(addr.base(EBP).index(R13D).scale(2).to_str(), "(%ebp, %r13d, 2)");
    EXPECT_EQ(addr.base(EBP).index(R14D).scale(4).to_str(), "(%ebp, %r14d, 4)");
    EXPECT_EQ(addr.base(EBP).index(R15D).scale(8).to_str(), "(%ebp, %r15d, 8)");

    EXPECT_EQ(addr.base(ESI).index(EAX).scale(1).to_str(), "(%esi, %eax, 1)");
    EXPECT_EQ(addr.base(ESI).index(EBX).scale(2).to_str(), "(%esi, %ebx, 2)");
    EXPECT_EQ(addr.base(ESI).index(ECX).scale(4).to_str(), "(%esi, %ecx, 4)");
    EXPECT_EQ(addr.base(ESI).index(EDX).scale(8).to_str(), "(%esi, %edx, 8)");
    EXPECT_EQ(addr.base(ESI).index(EBP).scale(1).to_str(), "(%esi, %ebp, 1)");
    EXPECT_EQ(addr.base(ESI).index(ESI).scale(2).to_str(), "(%esi, %esi, 2)");
    EXPECT_EQ(addr.base(ESI).index(EDI).scale(4).to_str(), "(%esi, %edi, 4)");
    EXPECT_EQ(addr.base(ESI).index(ESP).scale(8).to_str(), "(%esi, %esp, 8)");
    EXPECT_EQ(addr.base(ESI).index(R8D).scale(1).to_str(), "(%esi, %r8d, 1)");
    EXPECT_EQ(addr.base(ESI).index(R9D).scale(2).to_str(), "(%esi, %r9d, 2)");
    EXPECT_EQ(addr.base(ESI).index(R10D).scale(4).to_str(), "(%esi, %r10d, 4)");
    EXPECT_EQ(addr.base(ESI).index(R11D).scale(8).to_str(), "(%esi, %r11d, 8)");
    EXPECT_EQ(addr.base(ESI).index(R12D).scale(1).to_str(), "(%esi, %r12d, 1)");
    EXPECT_EQ(addr.base(ESI).index(R13D).scale(2).to_str(), "(%esi, %r13d, 2)");
    EXPECT_EQ(addr.base(ESI).index(R14D).scale(4).to_str(), "(%esi, %r14d, 4)");
    EXPECT_EQ(addr.base(ESI).index(R15D).scale(8).to_str(), "(%esi, %r15d, 8)");

    EXPECT_EQ(addr.base(EDI).index(EAX).scale(1).to_str(), "(%edi, %eax, 1)");
    EXPECT_EQ(addr.base(EDI).index(EBX).scale(2).to_str(), "(%edi, %ebx, 2)");
    EXPECT_EQ(addr.base(EDI).index(ECX).scale(4).to_str(), "(%edi, %ecx, 4)");
    EXPECT_EQ(addr.base(EDI).index(EDX).scale(8).to_str(), "(%edi, %edx, 8)");
    EXPECT_EQ(addr.base(EDI).index(EBP).scale(1).to_str(), "(%edi, %ebp, 1)");
    EXPECT_EQ(addr.base(EDI).index(ESI).scale(2).to_str(), "(%edi, %esi, 2)");
    EXPECT_EQ(addr.base(EDI).index(EDI).scale(4).to_str(), "(%edi, %edi, 4)");
    EXPECT_EQ(addr.base(EDI).index(ESP).scale(8).to_str(), "(%edi, %esp, 8)");
    EXPECT_EQ(addr.base(EDI).index(R8D).scale(1).to_str(), "(%edi, %r8d, 1)");
    EXPECT_EQ(addr.base(EDI).index(R9D).scale(2).to_str(), "(%edi, %r9d, 2)");
    EXPECT_EQ(addr.base(EDI).index(R10D).scale(4).to_str(), "(%edi, %r10d, 4)");
    EXPECT_EQ(addr.base(EDI).index(R11D).scale(8).to_str(), "(%edi, %r11d, 8)");
    EXPECT_EQ(addr.base(EDI).index(R12D).scale(1).to_str(), "(%edi, %r12d, 1)");
    EXPECT_EQ(addr.base(EDI).index(R13D).scale(2).to_str(), "(%edi, %r13d, 2)");
    EXPECT_EQ(addr.base(EDI).index(R14D).scale(4).to_str(), "(%edi, %r14d, 4)");
    EXPECT_EQ(addr.base(EDI).index(R15D).scale(8).to_str(), "(%edi, %r15d, 8)");

    EXPECT_EQ(addr.base(ESP).index(EAX).scale(1).to_str(), "(%esp, %eax, 1)");
    EXPECT_EQ(addr.base(ESP).index(EBX).scale(2).to_str(), "(%esp, %ebx, 2)");
    EXPECT_EQ(addr.base(ESP).index(ECX).scale(4).to_str(), "(%esp, %ecx, 4)");
    EXPECT_EQ(addr.base(ESP).index(EDX).scale(8).to_str(), "(%esp, %edx, 8)");
    EXPECT_EQ(addr.base(ESP).index(EBP).scale(1).to_str(), "(%esp, %ebp, 1)");
    EXPECT_EQ(addr.base(ESP).index(ESI).scale(2).to_str(), "(%esp, %esi, 2)");
    EXPECT_EQ(addr.base(ESP).index(EDI).scale(4).to_str(), "(%esp, %edi, 4)");
    EXPECT_EQ(addr.base(ESP).index(ESP).scale(8).to_str(), "(%esp, %esp, 8)");
    EXPECT_EQ(addr.base(ESP).index(R8D).scale(1).to_str(), "(%esp, %r8d, 1)");
    EXPECT_EQ(addr.base(ESP).index(R9D).scale(2).to_str(), "(%esp, %r9d, 2)");
    EXPECT_EQ(addr.base(ESP).index(R10D).scale(4).to_str(), "(%esp, %r10d, 4)");
    EXPECT_EQ(addr.base(ESP).index(R11D).scale(8).to_str(), "(%esp, %r11d, 8)");
    EXPECT_EQ(addr.base(ESP).index(R12D).scale(1).to_str(), "(%esp, %r12d, 1)");
    EXPECT_EQ(addr.base(ESP).index(R13D).scale(2).to_str(), "(%esp, %r13d, 2)");
    EXPECT_EQ(addr.base(ESP).index(R14D).scale(4).to_str(), "(%esp, %r14d, 4)");
    EXPECT_EQ(addr.base(ESP).index(R15D).scale(8).to_str(), "(%esp, %r15d, 8)");

    EXPECT_EQ(addr.base(R8D).index(EAX).scale(1).to_str(), "(%r8d, %eax, 1)");
    EXPECT_EQ(addr.base(R8D).index(EBX).scale(2).to_str(), "(%r8d, %ebx, 2)");
    EXPECT_EQ(addr.base(R8D).index(ECX).scale(4).to_str(), "(%r8d, %ecx, 4)");
    EXPECT_EQ(addr.base(R8D).index(EDX).scale(8).to_str(), "(%r8d, %edx, 8)");
    EXPECT_EQ(addr.base(R8D).index(EBP).scale(1).to_str(), "(%r8d, %ebp, 1)");
    EXPECT_EQ(addr.base(R8D).index(ESI).scale(2).to_str(), "(%r8d, %esi, 2)");
    EXPECT_EQ(addr.base(R8D).index(EDI).scale(4).to_str(), "(%r8d, %edi, 4)");
    EXPECT_EQ(addr.base(R8D).index(ESP).scale(8).to_str(), "(%r8d, %esp, 8)");
    EXPECT_EQ(addr.base(R8D).index(R8D).scale(1).to_str(), "(%r8d, %r8d, 1)");
    EXPECT_EQ(addr.base(R8D).index(R9D).scale(2).to_str(), "(%r8d, %r9d, 2)");
    EXPECT_EQ(addr.base(R8D).index(R10D).scale(4).to_str(), "(%r8d, %r10d, 4)");
    EXPECT_EQ(addr.base(R8D).index(R11D).scale(8).to_str(), "(%r8d, %r11d, 8)");
    EXPECT_EQ(addr.base(R8D).index(R12D).scale(1).to_str(), "(%r8d, %r12d, 1)");
    EXPECT_EQ(addr.base(R8D).index(R13D).scale(2).to_str(), "(%r8d, %r13d, 2)");
    EXPECT_EQ(addr.base(R8D).index(R14D).scale(4).to_str(), "(%r8d, %r14d, 4)");
    EXPECT_EQ(addr.base(R8D).index(R15D).scale(8).to_str(), "(%r8d, %r15d, 8)");

    EXPECT_EQ(addr.base(R9D).index(EAX).scale(1).to_str(), "(%r9d, %eax, 1)");
    EXPECT_EQ(addr.base(R9D).index(EBX).scale(2).to_str(), "(%r9d, %ebx, 2)");
    EXPECT_EQ(addr.base(R9D).index(ECX).scale(4).to_str(), "(%r9d, %ecx, 4)");
    EXPECT_EQ(addr.base(R9D).index(EDX).scale(8).to_str(), "(%r9d, %edx, 8)");
    EXPECT_EQ(addr.base(R9D).index(EBP).scale(1).to_str(), "(%r9d, %ebp, 1)");
    EXPECT_EQ(addr.base(R9D).index(ESI).scale(2).to_str(), "(%r9d, %esi, 2)");
    EXPECT_EQ(addr.base(R9D).index(EDI).scale(4).to_str(), "(%r9d, %edi, 4)");
    EXPECT_EQ(addr.base(R9D).index(ESP).scale(8).to_str(), "(%r9d, %esp, 8)");
    EXPECT_EQ(addr.base(R9D).index(R8D).scale(1).to_str(), "(%r9d, %r8d, 1)");
    EXPECT_EQ(addr.base(R9D).index(R9D).scale(2).to_str(), "(%r9d, %r9d, 2)");
    EXPECT_EQ(addr.base(R9D).index(R10D).scale(4).to_str(), "(%r9d, %r10d, 4)");
    EXPECT_EQ(addr.base(R9D).index(R11D).scale(8).to_str(), "(%r9d, %r11d, 8)");
    EXPECT_EQ(addr.base(R9D).index(R12D).scale(1).to_str(), "(%r9d, %r12d, 1)");
    EXPECT_EQ(addr.base(R9D).index(R13D).scale(2).to_str(), "(%r9d, %r13d, 2)");
    EXPECT_EQ(addr.base(R9D).index(R14D).scale(4).to_str(), "(%r9d, %r14d, 4)");
    EXPECT_EQ(addr.base(R9D).index(R15D).scale(8).to_str(), "(%r9d, %r15d, 8)");

    EXPECT_EQ(addr.base(R10D).index(EAX).scale(1).to_str(), "(%r10d, %eax, 1)");
    EXPECT_EQ(addr.base(R10D).index(EBX).scale(2).to_str(), "(%r10d, %ebx, 2)");
    EXPECT_EQ(addr.base(R10D).index(ECX).scale(4).to_str(), "(%r10d, %ecx, 4)");
    EXPECT_EQ(addr.base(R10D).index(EDX).scale(8).to_str(), "(%r10d, %edx, 8)");
    EXPECT_EQ(addr.base(R10D).index(EBP).scale(1).to_str(), "(%r10d, %ebp, 1)");
    EXPECT_EQ(addr.base(R10D).index(ESI).scale(2).to_str(), "(%r10d, %esi, 2)");
    EXPECT_EQ(addr.base(R10D).index(EDI).scale(4).to_str(), "(%r10d, %edi, 4)");
    EXPECT_EQ(addr.base(R10D).index(ESP).scale(8).to_str(), "(%r10d, %esp, 8)");
    EXPECT_EQ(addr.base(R10D).index(R8D).scale(1).to_str(), "(%r10d, %r8d, 1)");
    EXPECT_EQ(addr.base(R10D).index(R9D).scale(2).to_str(), "(%r10d, %r9d, 2)");
    EXPECT_EQ(addr.base(R10D).index(R10D).scale(4).to_str(), "(%r10d, %r10d, 4)");
    EXPECT_EQ(addr.base(R10D).index(R11D).scale(8).to_str(), "(%r10d, %r11d, 8)");
    EXPECT_EQ(addr.base(R10D).index(R12D).scale(1).to_str(), "(%r10d, %r12d, 1)");
    EXPECT_EQ(addr.base(R10D).index(R13D).scale(2).to_str(), "(%r10d, %r13d, 2)");
    EXPECT_EQ(addr.base(R10D).index(R14D).scale(4).to_str(), "(%r10d, %r14d, 4)");
    EXPECT_EQ(addr.base(R10D).index(R15D).scale(8).to_str(), "(%r10d, %r15d, 8)");

    EXPECT_EQ(addr.base(R11D).index(EAX).scale(1).to_str(), "(%r11d, %eax, 1)");
    EXPECT_EQ(addr.base(R11D).index(EBX).scale(2).to_str(), "(%r11d, %ebx, 2)");
    EXPECT_EQ(addr.base(R11D).index(ECX).scale(4).to_str(), "(%r11d, %ecx, 4)");
    EXPECT_EQ(addr.base(R11D).index(EDX).scale(8).to_str(), "(%r11d, %edx, 8)");
    EXPECT_EQ(addr.base(R11D).index(EBP).scale(1).to_str(), "(%r11d, %ebp, 1)");
    EXPECT_EQ(addr.base(R11D).index(ESI).scale(2).to_str(), "(%r11d, %esi, 2)");
    EXPECT_EQ(addr.base(R11D).index(EDI).scale(4).to_str(), "(%r11d, %edi, 4)");
    EXPECT_EQ(addr.base(R11D).index(ESP).scale(8).to_str(), "(%r11d, %esp, 8)");
    EXPECT_EQ(addr.base(R11D).index(R8D).scale(1).to_str(), "(%r11d, %r8d, 1)");
    EXPECT_EQ(addr.base(R11D).index(R9D).scale(2).to_str(), "(%r11d, %r9d, 2)");
    EXPECT_EQ(addr.base(R11D).index(R10D).scale(4).to_str(), "(%r11d, %r10d, 4)");
    EXPECT_EQ(addr.base(R11D).index(R11D).scale(8).to_str(), "(%r11d, %r11d, 8)");
    EXPECT_EQ(addr.base(R11D).index(R12D).scale(1).to_str(), "(%r11d, %r12d, 1)");
    EXPECT_EQ(addr.base(R11D).index(R13D).scale(2).to_str(), "(%r11d, %r13d, 2)");
    EXPECT_EQ(addr.base(R11D).index(R14D).scale(4).to_str(), "(%r11d, %r14d, 4)");
    EXPECT_EQ(addr.base(R11D).index(R15D).scale(8).to_str(), "(%r11d, %r15d, 8)");

    EXPECT_EQ(addr.base(R12D).index(EAX).scale(1).to_str(), "(%r12d, %eax, 1)");
    EXPECT_EQ(addr.base(R12D).index(EBX).scale(2).to_str(), "(%r12d, %ebx, 2)");
    EXPECT_EQ(addr.base(R12D).index(ECX).scale(4).to_str(), "(%r12d, %ecx, 4)");
    EXPECT_EQ(addr.base(R12D).index(EDX).scale(8).to_str(), "(%r12d, %edx, 8)");
    EXPECT_EQ(addr.base(R12D).index(EBP).scale(1).to_str(), "(%r12d, %ebp, 1)");
    EXPECT_EQ(addr.base(R12D).index(ESI).scale(2).to_str(), "(%r12d, %esi, 2)");
    EXPECT_EQ(addr.base(R12D).index(EDI).scale(4).to_str(), "(%r12d, %edi, 4)");
    EXPECT_EQ(addr.base(R12D).index(ESP).scale(8).to_str(), "(%r12d, %esp, 8)");
    EXPECT_EQ(addr.base(R12D).index(R8D).scale(1).to_str(), "(%r12d, %r8d, 1)");
    EXPECT_EQ(addr.base(R12D).index(R9D).scale(2).to_str(), "(%r12d, %r9d, 2)");
    EXPECT_EQ(addr.base(R12D).index(R10D).scale(4).to_str(), "(%r12d, %r10d, 4)");
    EXPECT_EQ(addr.base(R12D).index(R11D).scale(8).to_str(), "(%r12d, %r11d, 8)");
    EXPECT_EQ(addr.base(R12D).index(R12D).scale(1).to_str(), "(%r12d, %r12d, 1)");
    EXPECT_EQ(addr.base(R12D).index(R13D).scale(2).to_str(), "(%r12d, %r13d, 2)");
    EXPECT_EQ(addr.base(R12D).index(R14D).scale(4).to_str(), "(%r12d, %r14d, 4)");
    EXPECT_EQ(addr.base(R12D).index(R15D).scale(8).to_str(), "(%r12d, %r15d, 8)");

    EXPECT_EQ(addr.base(R13D).index(EAX).scale(1).to_str(), "(%r13d, %eax, 1)");
    EXPECT_EQ(addr.base(R13D).index(EBX).scale(2).to_str(), "(%r13d, %ebx, 2)");
    EXPECT_EQ(addr.base(R13D).index(ECX).scale(4).to_str(), "(%r13d, %ecx, 4)");
    EXPECT_EQ(addr.base(R13D).index(EDX).scale(8).to_str(), "(%r13d, %edx, 8)");
    EXPECT_EQ(addr.base(R13D).index(EBP).scale(1).to_str(), "(%r13d, %ebp, 1)");
    EXPECT_EQ(addr.base(R13D).index(ESI).scale(2).to_str(), "(%r13d, %esi, 2)");
    EXPECT_EQ(addr.base(R13D).index(EDI).scale(4).to_str(), "(%r13d, %edi, 4)");
    EXPECT_EQ(addr.base(R13D).index(ESP).scale(8).to_str(), "(%r13d, %esp, 8)");
    EXPECT_EQ(addr.base(R13D).index(R8D).scale(1).to_str(), "(%r13d, %r8d, 1)");
    EXPECT_EQ(addr.base(R13D).index(R9D).scale(2).to_str(), "(%r13d, %r9d, 2)");
    EXPECT_EQ(addr.base(R13D).index(R10D).scale(4).to_str(), "(%r13d, %r10d, 4)");
    EXPECT_EQ(addr.base(R13D).index(R11D).scale(8).to_str(), "(%r13d, %r11d, 8)");
    EXPECT_EQ(addr.base(R13D).index(R12D).scale(1).to_str(), "(%r13d, %r12d, 1)");
    EXPECT_EQ(addr.base(R13D).index(R13D).scale(2).to_str(), "(%r13d, %r13d, 2)");
    EXPECT_EQ(addr.base(R13D).index(R14D).scale(4).to_str(), "(%r13d, %r14d, 4)");
    EXPECT_EQ(addr.base(R13D).index(R15D).scale(8).to_str(), "(%r13d, %r15d, 8)");

    EXPECT_EQ(addr.base(R14D).index(EAX).scale(1).to_str(), "(%r14d, %eax, 1)");
    EXPECT_EQ(addr.base(R14D).index(EBX).scale(2).to_str(), "(%r14d, %ebx, 2)");
    EXPECT_EQ(addr.base(R14D).index(ECX).scale(4).to_str(), "(%r14d, %ecx, 4)");
    EXPECT_EQ(addr.base(R14D).index(EDX).scale(8).to_str(), "(%r14d, %edx, 8)");
    EXPECT_EQ(addr.base(R14D).index(EBP).scale(1).to_str(), "(%r14d, %ebp, 1)");
    EXPECT_EQ(addr.base(R14D).index(ESI).scale(2).to_str(), "(%r14d, %esi, 2)");
    EXPECT_EQ(addr.base(R14D).index(EDI).scale(4).to_str(), "(%r14d, %edi, 4)");
    EXPECT_EQ(addr.base(R14D).index(ESP).scale(8).to_str(), "(%r14d, %esp, 8)");
    EXPECT_EQ(addr.base(R14D).index(R8D).scale(1).to_str(), "(%r14d, %r8d, 1)");
    EXPECT_EQ(addr.base(R14D).index(R9D).scale(2).to_str(), "(%r14d, %r9d, 2)");
    EXPECT_EQ(addr.base(R14D).index(R10D).scale(4).to_str(), "(%r14d, %r10d, 4)");
    EXPECT_EQ(addr.base(R14D).index(R11D).scale(8).to_str(), "(%r14d, %r11d, 8)");
    EXPECT_EQ(addr.base(R14D).index(R12D).scale(1).to_str(), "(%r14d, %r12d, 1)");
    EXPECT_EQ(addr.base(R14D).index(R13D).scale(2).to_str(), "(%r14d, %r13d, 2)");
    EXPECT_EQ(addr.base(R14D).index(R14D).scale(4).to_str(), "(%r14d, %r14d, 4)");
    EXPECT_EQ(addr.base(R14D).index(R15D).scale(8).to_str(), "(%r14d, %r15d, 8)");

    EXPECT_EQ(addr.base(R15D).index(EAX).scale(1).to_str(), "(%r15d, %eax, 1)");
    EXPECT_EQ(addr.base(R15D).index(EBX).scale(2).to_str(), "(%r15d, %ebx, 2)");
    EXPECT_EQ(addr.base(R15D).index(ECX).scale(4).to_str(), "(%r15d, %ecx, 4)");
    EXPECT_EQ(addr.base(R15D).index(EDX).scale(8).to_str(), "(%r15d, %edx, 8)");
    EXPECT_EQ(addr.base(R15D).index(EBP).scale(1).to_str(), "(%r15d, %ebp, 1)");
    EXPECT_EQ(addr.base(R15D).index(ESI).scale(2).to_str(), "(%r15d, %esi, 2)");
    EXPECT_EQ(addr.base(R15D).index(EDI).scale(4).to_str(), "(%r15d, %edi, 4)");
    EXPECT_EQ(addr.base(R15D).index(ESP).scale(8).to_str(), "(%r15d, %esp, 8)");
    EXPECT_EQ(addr.base(R15D).index(R8D).scale(1).to_str(), "(%r15d, %r8d, 1)");
    EXPECT_EQ(addr.base(R15D).index(R9D).scale(2).to_str(), "(%r15d, %r9d, 2)");
    EXPECT_EQ(addr.base(R15D).index(R10D).scale(4).to_str(), "(%r15d, %r10d, 4)");
    EXPECT_EQ(addr.base(R15D).index(R11D).scale(8).to_str(), "(%r15d, %r11d, 8)");
    EXPECT_EQ(addr.base(R15D).index(R12D).scale(1).to_str(), "(%r15d, %r12d, 1)");
    EXPECT_EQ(addr.base(R15D).index(R13D).scale(2).to_str(), "(%r15d, %r13d, 2)");
    EXPECT_EQ(addr.base(R15D).index(R14D).scale(4).to_str(), "(%r15d, %r14d, 4)");
    EXPECT_EQ(addr.base(R15D).index(R15D).scale(8).to_str(), "(%r15d, %r15d, 8)");
}
